const fs = require('fs');
let code = fs.readFileSync('server/routes.ts', 'utf8');

const targetStr = `  app.post("/api/pull-requests/action", (req, res) => {`;
const newStr = `  app.post("/api/sanity-checks/run/:runId/create-jira", async (req, res) => {
    try {
      const { runId } = req.params;
      const history = loadHistory();
      const run = history.find(r => r.id === runId);
      
      if (!run) {
        return res.status(404).json({ error: "Run not found" });
      }
      
      if (!run.pullRequest && !run.jiraIssueDraft) {
         return res.status(400).json({ error: "No Jira draft available for this run." });
      }
      
      let summary = run.jiraIssueDraft?.summary || run.pullRequest?.title || "OpsPilot Incident Fix";
      let description = run.jiraIssueDraft?.description || run.pullRequest?.description || run.executiveSummary || "";
      let suggestions = run.jiraIssueDraft?.suggestions || "Suggested fixes automatically generated by OpsPilot.";
      
      if (run.pullRequest && run.pullRequest.filesChanged) {
        suggestions += "\\n\\nFiles Changed:\\n";
        run.pullRequest.filesChanged.forEach(file => {
           suggestions += "- " + file.filename + "\\n";
        });
      }

      const jiraRes = await createJiraIssue(summary, description, suggestions);
      
      // Update history
      run.jiraIssueKey = jiraRes.key;
      run.jiraIssueLink = jiraRes.link;
      
      run.logs.push({
        timestamp: new Date().toISOString(),
        level: "success",
        message: \`[Jira Ticket Created] \${jiraRes.key} has been logged for this incident.\`,
        step: "pr_create"
      });
      
      addHistory(run);
      
      res.json(jiraRes);
    } catch (err: any) {
      console.error("Error creating Jira issue:", err);
      res.status(500).json({ error: err.message || "Failed to create Jira issue" });
    }
  });

  app.post("/api/pull-requests/action", (req, res) => {`;

code = code.replace(targetStr, newStr);

fs.writeFileSync('server/routes.ts', code);
